# Generated by Django 4.1.7 on 2023-03-21 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0002_remove_house_payments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="render",
        ),
        migrations.AddField(
            model_name="payment",
            name="house",
            field=models.ManyToManyField(blank=True, to="houses.house"),
        ),
        migrations.AddField(
            model_name="payment",
            name="time",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
