# Generated by Django 4.1.7 on 2023-03-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0002_remove_payment_render_payment_house_payment_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="time",
        ),
        migrations.AddField(
            model_name="payment",
            name="render",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
