# Generated by Django 4.2 on 2023-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0002_alter_payment_payment_alter_payment_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="price_b",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
