# Generated by Django 4.2 on 2023-04-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0005_payment_owner_alter_payment_render"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="houses"),
        ),
    ]
