# Generated by Django 4.1.7 on 2023-03-19 20:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("username", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("surname", models.CharField(blank=True, max_length=200, null=True)),
                ("phone", models.IntegerField(blank=True, null=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_superadmin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_mechanic", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("permissions", models.ManyToManyField(blank=True, to="auth.group")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
