# Generated by Django 4.1.7 on 2023-03-21 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkTime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("work_hour_start", models.TimeField(blank=True, null=True)),
                ("work_hour_end", models.TimeField(blank=True, null=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkCalc",
            fields=[
                (
                    "day",
                    models.TextField(
                        choices=[
                            ("0", "Normal"),
                            ("1", "Weekend"),
                            ("2", "Times off"),
                            ("3", "Sick leave"),
                            ("4", "Public holiday"),
                        ],
                        default="0",
                        max_length=2,
                    ),
                ),
                ("date", models.DateField()),
                ("start_of_work", models.TimeField(blank=True, null=True)),
                ("end_of_work", models.TimeField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
