# Generated by Django 4.1.7 on 2023-03-20 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("work_hours", "0002_worktime_created_worktime_modified_alter_worktime_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workcalc",
            options={"ordering": ["day"]},
        ),
    ]
