# Generated by Django 4.1.7 on 2023-03-20 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("work_hours", "0004_alter_worktime_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workcalc",
            options={"ordering": ["date"]},
        ),
    ]
